name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install uv and setup Python
        uses: astral-sh/setup-uv@v6.3.1
          with:
            enable-cache: true

      - name: Install the project
        run: uv sync --all-groups --all-extras

      - name: Build Wheel
        run: uv Build

      - name: Publish Package
        run: uv publish --trusted-publishing always
